# Deployment for packagemanage service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bugzilla
spec:
  selector:
    matchLabels:
      app: bugzilla
  template:
    metadata:
      labels:
        app: bugzilla
    spec:
      containers:
        - name: bugzilla-server
          image: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bugzilla
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
          command:
            - /bin/bash
            - -c
            - |
              sh ./cfg.sh
              a2ensite bugzilla
              a2enmod cgi headers expires
              service apache2 restart
              sleep infinity
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bugzilla-db
                  key: bugzilla-db-user
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: bugzilla-db
                  key: bugzilla-db-pwd
            - name: DB_ADDR
              valueFrom:
                secretKeyRef:
                  name: bugzilla-db
                  key: bugzilla-db-addr
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: bugzilla-db
                  key: bugzilla-db-port
